global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: "otel"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel:8889"]
      # - targets: ["otel:8888"]

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: [ 'tempo:3200' ]

  # - job_name: 'service'
  #   scrape_interval: 5s
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['dbservice:8080']
  #       labels:
  #         group: 'service'